/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DB_Item.DBConnection;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import control.Gardiyan;
import control.Mudur;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class LoginGUI extends javax.swing.JFrame {

    private DBConnection conn = new DBConnection();

    public LoginGUI() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/icons/adalet32.png")).getImage();
        this.setIconImage(icon);
        pnl_left.setBackground(new Color(0, 0, 0, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_right = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tckn_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        lbl_forgotPassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_error1 = new javax.swing.JLabel();
        lbl_error2 = new javax.swing.JLabel();
        pnl_cezaevi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_left.setBackground(new java.awt.Color(0, 0, 0));
        pnl_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cezaevi Otomasyon Sistemi");
        pnl_left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 50));

        getContentPane().add(pnl_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pnl_right.setBackground(new java.awt.Color(255, 255, 255));
        pnl_right.setForeground(new java.awt.Color(255, 255, 255));
        pnl_right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 18, 18));
        jLabel4.setText("TCKN");
        pnl_right.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 18, 18));
        jLabel5.setText("Şifre");
        pnl_right.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        tckn_field.setBackground(new java.awt.Color(255, 255, 255));
        tckn_field.setForeground(new java.awt.Color(0, 0, 0));
        tckn_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        pnl_right.add(tckn_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, 30));

        password_field.setBackground(new java.awt.Color(255, 255, 255));
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        pnl_right.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 30));
        pnl_right.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 314, 130, 10));
        pnl_right.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 314, 130, 10));

        btn_login.setBackground(new java.awt.Color(24, 119, 242));
        btn_login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Giriş yap");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_right.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 330, 30));

        lbl_forgotPassword.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_forgotPassword.setForeground(new java.awt.Color(24, 119, 242));
        lbl_forgotPassword.setText("Şifreni mi unuttun?");
        lbl_forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotPasswordMouseClicked(evt);
            }
        });
        pnl_right.add(lbl_forgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(80, 82, 84));
        jLabel3.setText("YA DA");
        pnl_right.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 306, -1, 20));

        btn_create.setBackground(new java.awt.Color(102, 102, 102));
        btn_create.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("Hesap Oluştur");
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createMouseClicked(evt);
            }
        });
        pnl_right.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, 30));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Mertcan Akdaş , Nuhhan Bozdemir | proje ödevi");
        pnl_right.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        lbl_error1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_error1.setText("Burası boş bırakılamaz");
        pnl_right.add(lbl_error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 330, -1));

        lbl_error2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_error2.setText("Burası boş bırakılamaz");
        pnl_right.add(lbl_error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, -1));

        getContentPane().add(pnl_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 450));

        pnl_cezaevi.setBackground(new java.awt.Color(0, 0, 0));
        pnl_cezaevi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cezaevi.jpg"))); // NOI18N
        getContentPane().add(pnl_cezaevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseClicked
        RegisterGUI registerGUI = new RegisterGUI();
        registerGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_createMouseClicked

    private void lbl_forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotPasswordMouseClicked
        ResetPasswordGUI resetPasswordGUI = new ResetPasswordGUI();
        resetPasswordGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_forgotPasswordMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if (tckn_field.getText().length() == 0 && password_field.getText().length() == 0) {
            lbl_error1.setForeground(Color.red);
            lbl_error2.setForeground(Color.red);
        } else {
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM memurlar");

                while (rs.next()) {
                    if (tckn_field.getText().equals(rs.getString("TCKN")) && password_field.getText().equals(rs.getString("Password"))) {
                        if (rs.getString("Type").equals("Gardiyan")) {
                            Gardiyan gardiyan = new Gardiyan();
                            gardiyan.setId(rs.getInt("ID"));
                            gardiyan.setTckn(rs.getString("TCKN"));
                            gardiyan.setName(rs.getString("Name"));
                            gardiyan.setPassword(rs.getString("Password"));
                            gardiyan.setType(rs.getString("Type"));
                            GardiyanGUI gardiyanGUI = new GardiyanGUI(gardiyan);
                            gardiyanGUI.setVisible(true);
                            dispose();
                        } else if (rs.getString("Type").equals("Müdür")) {
                            Mudur mudur = new Mudur();
                            mudur.setId(rs.getInt("ID"));
                            mudur.setTckn(rs.getString("TCKN"));
                            mudur.setName(rs.getString("Name"));
                            mudur.setPassword(rs.getString("Password"));
                            mudur.setType(rs.getString("Type"));
                            MudurGUI mudurGUI = new MudurGUI(mudur);
                            mudurGUI.setVisible(true);
                            dispose();
                        }

                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_error1;
    private javax.swing.JLabel lbl_error2;
    private javax.swing.JLabel lbl_forgotPassword;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel pnl_cezaevi;
    private javax.swing.JPanel pnl_left;
    private javax.swing.JPanel pnl_right;
    private javax.swing.JTextField tckn_field;
    // End of variables declaration//GEN-END:variables
}
