/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import control.Gardiyan;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class RegisterGUI extends javax.swing.JFrame {

    static Gardiyan gardiyan = new Gardiyan();
    
    
    public RegisterGUI() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/icons/adalet32.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_wrapper = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        tckn_field = new javax.swing.JTextField();
        lbl_pass = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        lbl_tckn = new javax.swing.JLabel();
        lbl_confirm = new javax.swing.JLabel();
        confirm_field = new javax.swing.JPasswordField();
        userName_field = new javax.swing.JTextField();
        lbl_userName = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        lbl_turnBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_wrapper.setBackground(new java.awt.Color(255, 255, 255));
        pnl_wrapper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_welcome.setBackground(new java.awt.Color(255, 255, 255));
        lbl_welcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(18, 18, 18));
        lbl_welcome.setText("Hoşgeldiniz");
        pnl_wrapper.add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        tckn_field.setBackground(new java.awt.Color(255, 255, 255));
        tckn_field.setForeground(new java.awt.Color(0, 0, 0));
        tckn_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        tckn_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckn_fieldActionPerformed(evt);
            }
        });
        tckn_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tckn_fieldKeyPressed(evt);
            }
        });
        pnl_wrapper.add(tckn_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, 30));

        lbl_pass.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(18, 18, 18));
        lbl_pass.setText("Şifre");
        pnl_wrapper.add(lbl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        password_field.setBackground(new java.awt.Color(255, 255, 255));
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        pnl_wrapper.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, 30));

        lbl_tckn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_tckn.setForeground(new java.awt.Color(18, 18, 18));
        lbl_tckn.setText("TCKN");
        pnl_wrapper.add(lbl_tckn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lbl_confirm.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_confirm.setForeground(new java.awt.Color(18, 18, 18));
        lbl_confirm.setText("Şifreyi onaylayın");
        pnl_wrapper.add(lbl_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        confirm_field.setBackground(new java.awt.Color(255, 255, 255));
        confirm_field.setForeground(new java.awt.Color(0, 0, 0));
        confirm_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });
        confirm_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_fieldKeyPressed(evt);
            }
        });
        pnl_wrapper.add(confirm_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 330, 30));

        userName_field.setBackground(new java.awt.Color(255, 255, 255));
        userName_field.setForeground(new java.awt.Color(0, 0, 0));
        userName_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        userName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_fieldActionPerformed(evt);
            }
        });
        userName_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName_fieldKeyPressed(evt);
            }
        });
        pnl_wrapper.add(userName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 330, 30));

        lbl_userName.setBackground(new java.awt.Color(255, 255, 255));
        lbl_userName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(18, 18, 18));
        lbl_userName.setText("Kullanıcı Adı");
        pnl_wrapper.add(lbl_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btn_create.setBackground(new java.awt.Color(102, 102, 102));
        btn_create.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("Hesap Oluştur");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        pnl_wrapper.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 330, 30));

        error1.setForeground(new java.awt.Color(255, 255, 255));
        error1.setText("Bu kısım boş bırakılamaz");
        pnl_wrapper.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 330, -1));

        error2.setForeground(new java.awt.Color(255, 255, 255));
        error2.setText("Bu kısım boş bırakılamaz");
        pnl_wrapper.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, -1));

        error3.setForeground(new java.awt.Color(255, 255, 255));
        error3.setText("Bu kısım boş bırakılamaz");
        pnl_wrapper.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 330, -1));

        error4.setForeground(new java.awt.Color(255, 255, 255));
        error4.setText("Bu kısım boş bırakılamaz");
        pnl_wrapper.add(error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, -1));

        lbl_turnBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_turnBack.setForeground(new java.awt.Color(24, 119, 242));
        lbl_turnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back16px.png"))); // NOI18N
        lbl_turnBack.setText("Geri dön");
        lbl_turnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_turnBackMouseClicked(evt);
            }
        });
        pnl_wrapper.add(lbl_turnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        getContentPane().add(pnl_wrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void lbl_turnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_turnBackMouseClicked
        LoginGUI loginGUI = new LoginGUI();
        loginGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_turnBackMouseClicked

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        if (!password_field.getText().equals(confirm_field.getText())) {
                UIManager.put("OptionPane.okButtonText", "Tamam");
                JOptionPane.showMessageDialog(rootPane, "Şifre ve şifreyi doğrulayın kısmı aynı olmalı");
                
            }
        
        if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error2.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
            error2.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(Color.red);
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error2.setForeground(Color.red);
            error3.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error2.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() != 0 && tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error3.setForeground(Color.red);
            error4.setForeground(Color.red);
        } else if (userName_field.getText().length() == 0 && tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(Color.red);
            error2.setForeground(Color.red);
            error3.setForeground(Color.red);
            error4.setForeground(Color.red);
           
        } else {
            try {
                if (password_field.getText().equals(confirm_field.getText())) {
                    String upperAd = userName_field.getText().substring(0, 1).toUpperCase() + userName_field.getText().substring(1);

                boolean control = gardiyan.addGardiyan(tckn_field.getText(), upperAd, password_field.getText());
                if (control) {
                    UIManager.put("OptionPane.okButtonText", "Tamam");
                    JOptionPane.showMessageDialog(rootPane, "Kayıt başarılı", "Memur Kayıt", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/icons/Done.png")));
                    userName_field.setText(null);
                    tckn_field.setText(null);
                    password_field.setText(null);
                    confirm_field.setText(null);
                }else{
                     UIManager.put("OptionPane.okButtonText", "Tamam");
                     JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız", "Memur Kayıt", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/icons/CloseRed48px.png")));
                }
            } 
                }catch (Exception e) {
                e.printStackTrace();
            }
                
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void userName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_fieldActionPerformed
        
    }//GEN-LAST:event_userName_fieldActionPerformed

    private void tckn_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckn_fieldActionPerformed
       
    }//GEN-LAST:event_tckn_fieldActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
       
    }//GEN-LAST:event_password_fieldActionPerformed

    private void userName_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName_fieldKeyPressed
        error1.setForeground(Color.WHITE);
    }//GEN-LAST:event_userName_fieldKeyPressed

    private void tckn_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tckn_fieldKeyPressed
        error2.setForeground(Color.WHITE);
    }//GEN-LAST:event_tckn_fieldKeyPressed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        error3.setForeground(Color.WHITE);
    }//GEN-LAST:event_password_fieldKeyPressed

    private void confirm_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_fieldKeyPressed
       error4.setForeground(Color.WHITE);
    }//GEN-LAST:event_confirm_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JPasswordField confirm_field;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel lbl_confirm;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_tckn;
    private javax.swing.JLabel lbl_turnBack;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JPanel pnl_wrapper;
    private javax.swing.JTextField tckn_field;
    private javax.swing.JTextField userName_field;
    // End of variables declaration//GEN-END:variables
}
