/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DB_Item.DBConnection;
import com.formdev.flatlaf.FlatLightLaf;
import control.Gardiyan;
import control.Mudur;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class ResetPasswordGUI extends javax.swing.JFrame {

    private DBConnection conn = new DBConnection();
    static Gardiyan gardiyan = new Gardiyan();
    static Mudur mudur = new Mudur();

    org.mariadb.jdbc.Statement st = null;
    ResultSet rs = null;
    org.mariadb.jdbc.Connection con = (org.mariadb.jdbc.Connection) conn.connDB();
    PreparedStatement preparedStatement = null;

    public ResetPasswordGUI() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/icons/adalet32.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tckn = new javax.swing.JLabel();
        tckn_field = new javax.swing.JTextField();
        lbl_turnBack = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        error2 = new javax.swing.JLabel();
        lbl_confirm = new javax.swing.JLabel();
        confirm_field = new javax.swing.JPasswordField();
        error3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tckn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_tckn.setForeground(new java.awt.Color(18, 18, 18));
        lbl_tckn.setText("TCKN");
        jPanel1.add(lbl_tckn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        tckn_field.setBackground(new java.awt.Color(255, 255, 255));
        tckn_field.setForeground(new java.awt.Color(0, 0, 0));
        tckn_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        tckn_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckn_fieldActionPerformed(evt);
            }
        });
        tckn_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tckn_fieldKeyPressed(evt);
            }
        });
        jPanel1.add(tckn_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 330, 30));

        lbl_turnBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_turnBack.setForeground(new java.awt.Color(24, 119, 242));
        lbl_turnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back16px.png"))); // NOI18N
        lbl_turnBack.setText("Geri dön");
        lbl_turnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_turnBackMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_turnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        lbl_welcome.setBackground(new java.awt.Color(0, 0, 0));
        lbl_welcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_welcome.setText("Kullananıcı hesabını kurtarma");
        jPanel1.add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel1.setForeground(new java.awt.Color(18, 18, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("TCKN kullanarak hesabınızı kurtarmayı deneyebilirsiniz");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 20));
        jLabel1.getAccessibleContext().setAccessibleName("TCKN kullanarak hesabınızı kurtarmayı \ndeneyebilirsiniz");

        jLabel2.setForeground(new java.awt.Color(18, 18, 18));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ADALET BAKANLIĞI LOGO PNG.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 70));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ADALET BAKANLIĞI");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 30));

        btn_next.setBackground(new java.awt.Color(24, 119, 242));
        btn_next.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 255, 255));
        btn_next.setText("İleri");
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nextMouseClicked(evt);
            }
        });
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel1.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 330, 30));

        error1.setForeground(new java.awt.Color(255, 255, 255));
        error1.setText("Bu kısım boş bırakılamaz");
        jPanel1.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 330, -1));

        lbl_pass.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(18, 18, 18));
        lbl_pass.setText("Yeni şifre");
        jPanel1.add(lbl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        password_field.setBackground(new java.awt.Color(255, 255, 255));
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        jPanel1.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 330, 30));

        error2.setForeground(new java.awt.Color(255, 255, 255));
        error2.setText("Bu kısım boş bırakılamaz");
        jPanel1.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 330, -1));

        lbl_confirm.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_confirm.setForeground(new java.awt.Color(18, 18, 18));
        lbl_confirm.setText("Şifreyi onaylayın");
        jPanel1.add(lbl_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        confirm_field.setBackground(new java.awt.Color(255, 255, 255));
        confirm_field.setForeground(new java.awt.Color(0, 0, 0));
        confirm_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });
        confirm_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirm_fieldKeyPressed(evt);
            }
        });
        jPanel1.add(confirm_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 330, 30));

        error3.setForeground(new java.awt.Color(255, 255, 255));
        error3.setText("Bu kısım boş bırakılamaz");
        jPanel1.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_turnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_turnBackMouseClicked
        LoginGUI loginGUI = new LoginGUI();
        loginGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_turnBackMouseClicked

    private void tckn_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckn_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tckn_fieldActionPerformed

    private void btn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseClicked

        if (tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(new Color(204, 0, 0));
            error2.setForeground(new Color(204, 0, 0));
            error3.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() == 0) {
            error2.setForeground(new Color(204, 0, 0));
            error3.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error1.setForeground(new Color(204, 0, 0));
            error3.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() == 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(new Color(204, 0, 0));
            error2.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() == 0 && password_field.getText().length() != 0 && confirm_field.getText().length() != 0) {
            error1.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() != 0 && password_field.getText().length() == 0 && confirm_field.getText().length() != 0) {
            error2.setForeground(new Color(204, 0, 0));
        } else if (tckn_field.getText().length() != 0 && password_field.getText().length() != 0 && confirm_field.getText().length() == 0) {
            error3.setForeground(new Color(204, 0, 0));
        } else if (!password_field.getText().equals(confirm_field.getText())) {
            UIManager.put("OptionPane.okButtonText", "Tamam");
            JOptionPane.showMessageDialog(rootPane, "Şifre ve şifreyi onaylayın kısmı aynı olmalı");

        } else {
            try {
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM memurlar");
                
                
                boolean control = updateMemur(password_field.getText(), tckn_field.getText());

                if (control) {
                    UIManager.put("OptionPane.okButtonText", "Tamam");
                    JOptionPane.showMessageDialog(rootPane, "Kayıt başarılı", "Memur kayıt", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/icons/Done.png")));
                    tckn_field.setText(null);
                    password_field.setText(null);
                    confirm_field.setText(null);
                } else {
                    UIManager.put("OptionPane.okButtonText", "Tamam");
                    JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız", "Memur Kayıt", JOptionPane.OK_OPTION, new ImageIcon(getClass().getResource("/icons/CloseRed48px.png")));
                }
                
                    
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btn_nextMouseClicked

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed

    }//GEN-LAST:event_btn_nextActionPerformed

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void tckn_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tckn_fieldKeyPressed
        error1.setForeground(Color.white);
    }//GEN-LAST:event_tckn_fieldKeyPressed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        error2.setForeground(Color.white);
    }//GEN-LAST:event_password_fieldKeyPressed

    private void confirm_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_fieldKeyPressed
        error3.setForeground(Color.white);
    }//GEN-LAST:event_confirm_fieldKeyPressed

    public boolean updateMemur(String password, String tckn) throws SQLException {
        boolean key = false;
        String query = "UPDATE memurlar SET Password = ? WHERE TCKN = ?";
        try {
            st = con.createStatement();
            preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, password);
            preparedStatement.setString(2, tckn);
            preparedStatement.executeUpdate();
            key = true;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (key) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPasswordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JPasswordField confirm_field;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_confirm;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_tckn;
    private javax.swing.JLabel lbl_turnBack;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField tckn_field;
    // End of variables declaration//GEN-END:variables
}
